// Generated by Wrangler on Fri Aug 16 2024 00:59:00 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	DB: D1Database;
}
