name = "a-app-worker"
compatibility_date = "2024-08-06"
send_metrics = false
main = "./.output/server/index.mjs"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "a-app-url-short"
database_id = "13769275-0589-4fac-a5f0-16a56689173d"
migrations_dir = "database"

[[kv_namespaces]]
binding = "KV"
id = "9d16d408f0874149a423d7b1b332037f"

[vars]
NUXT_DB_TYPE = "d1"
NUXT_CDNURL = "https://aapp.static.ttpos.com/"

[placement]
mode = "smart"
