name = "a-app-worker"
compatibility_date = "2024-08-06"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"
send_metrics = false

[[d1_databases]]
binding = "DB"
database_name = "a-app-url-short"
database_id = "13769275-0589-4fac-a5f0-16a56689173d"
migrations_dir = "database"

[[kv_namespaces]]
binding = "KV"
id = "9d16d408f0874149a423d7b1b332037f"

[vars]
NUXT_DB_TYPE = "d1"
