name = "a-app-links"
compatibility_date = "2024-08-06"
send_metrics = false
main = "./.output/server/index.mjs"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "a-app-links"
database_id = "abbfd748-2701-46c7-8f8a-b1f65b2964eb"
migrations_dir = "server/database"

[vars]
NUXT_DB_TYPE = "d1"

[placement]
mode = "smart"

[site]
bucket = ".output/empty"
