// Generated by Wrangler on Thu Sep 26 2024 11:15:03 GMT+0800 (China Standard Time)
// by running `wrangler types ./server/types/worker-configuration.d.ts`

export {};
declare global {
	const NUXT_DB_TYPE: "d1";
	const DB: D1Database;
}
