// Generated by Wrangler on Tue Oct 01 2024 10:25:54 GMT+0800 (China Standard Time)
// by running `wrangler types ./server/types/worker-configuration.d.ts`

export {};
declare global {
	const KV: KVNamespace;
	const NUXT_DB_TYPE: "d1";
	const DB: D1Database;
}
