// Generated by Wrangler on Thu Aug 29 2024 10:40:43 GMT+0800 (China Standard Time)
// by running `wrangler types ./server/types/worker-configuration.d.ts`

interface Env {
	KV: KVNamespace;
	NUXT_DB_TYPE: "d1";
	DB: D1Database;
}
