name = "url-shortener-api"
compatibility_date = "2024-08-14"
workers_dev = false
main = "src/index.ts"

kv_namespaces = [
  { binding = "URL_MAPPINGS", id = "2f7f2d502f53459a916080fdb5a568de" },
  { binding = "URL_ANALYTICS", id = "d46543f2c1754eef8e840fd6da277c08" },
  { binding = "API_KEYS", id = "d9a3e66559aa40139cdbb2b914531a96" },
  { binding = "OG_METADATA_CACHE", id = "7fa38cba5ef7492e813011ac0b4d49cc" }
]

[vars]
REDIRECT_URL = "https://rails.d.hj.io/"
ALLOWED_CORS_ORIGINS = "*"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
