name: Deploy User to Cloudflare worker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./apps/user
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Build and migrate database
        env:
          NUXT_DB_TYPE: d1
          NUXT_DEBUG: false
          NUXT_CDNURL: ${{ vars.USER_CDN_URL }}
          DEPLOY_RUNTIME: cloudflare-module
          PAGES_PROJECT: ${{ vars.USER_STATIC_PAGES }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_DATABASE_ID: ${{ vars.CLOUDFLARE_USER_DB }}
        run: |
          pnpm install
          pnpm db:gen
          pnpm db:migrate
          pnpm build
          pnpm cf:deploy
