name: Deploy user to Fly.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./apps/user
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
          POD_NAME: user
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          NUXT_PUBLIC_SITE_URL: ${{ vars.USER_URL }}
          NUXT_LIBSQL_URL: ${{ vars.USER_LIBSQL_URL }}
          NUXT_LIBSQL_AUTH_TOKEN: ${{ secrets.USER_LIBSQL_AUTH_TOKEN }}
        run: |
          ./aa build
          ./aa deploy
