name: Deploy dashboard to Fly.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./apps/dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
          POD_NAME: dashboard
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          NUXT_PUBLIC_SITE_URL: ${{ vars.URL_DASHBOARD_SITE }}
        run: |
          ./aa build
          ./aa deploy
