name: Test env

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: test env
        env:
          NUXT_DB_TYPE: d1
          NUXT_DEBUG: false
          NUXT_CDNURL: ${{ vars.LINKS_CDN_URL }}
          DEPLOY_RUNTIME: cloudflare-module
          PAGES_PROJECT: ${{ vars.LINKS_STATIC_PAGES }}
        run: |
          env
